name: Continuous Builder
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'metadata/**'
      - 'legal/**'
      - '**.md'
      - 'LICENSE'
      - '.github/workflows/release-builder.yml'
      - '.github/FUNDING.yml'
  pull_request:

jobs:
  build:
    name: Continuous Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
          
      - name: Setup JDK
        uses: actions/setup-java@v4
        with: 
          distribution: 'zulu'
          java-version: '17'
        
      - name: Build APK
        run: |
          ./gradlew build --stacktrace
          
      - name: List build output
        run: |
          cd app/build/outputs/apk/release/
          ls
